[package]
name = "dlopen"
version = "0.1.9"
rust="1.47.0"
readme = "README.md"
authors = ["Szymon Wieloch <szymon.wieloch@gmail.com>"]
description = "Library for opening and operating on dynamic link libraries (also known as shared objects or shared libraries). This is a modern and more flexible alternative to the already existing libraries like libloading or sharedlib"
keywords = [
    #common functions
    "dlopen", "dll", "so", "dylib", "shared"]
license = "MIT"
repository = "https://github.com/szymonwieloch/rust-dlopen"


[dependencies]
lazy_static = "1.4.0"
dlopen_derive = { path = "../rust-dlopen-derive", optional = true, version = "0.1.4" }

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3.9", features=["winnt", "minwindef", "winerror", "libloaderapi", "errhandlingapi", "dbghelp", "processthreadsapi", "basetsd"]}

[target.'cfg(unix)'.dependencies]
libc = "0.2.79"


[dev-dependencies]
const-cstr = "0.1"
libc = "0.2.79"
regex = "0.2"
example_dylib = { path = "../rust-example-dylib", version = "0.1.0" }

[features]
default = ["derive"]
derive = ["dlopen_derive"]